# Generated by Django 5.2.1 on 2025-05-20 01:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('visit_to', models.CharField(choices=[('tony', 'Tony Cox-Smith'), ('ann', 'Ann Mansoor'), ('joanna', 'Joanna Wu'), ('mele', 'Mele Tatafu'), ('vicky', 'Weidi Qu'), ('emily', 'Emily Donovan'), ('ray', 'Ray Lee'), ('ricky', 'Richard Light'), ('cy', 'Chim Yun Cheng'), ('julie', 'Julie Ullness')], help_text='Who are you visiting', max_length=40)),
            ],
        ),
    ]
